
const RACES = {
  NONE:{id:'NONE', text:''},
  BEORNING: {id:'BEORNING', text:'Beorning'},
  DWARF: {id:'DWARF',text:'Dwarf'},
  HIGH_ELF:{id:'HIGH_ELF',text:'High Elf'},
  HOBBIT:{id:'HOBBIT', text:'Hobbit'},
  HUMAN:{id:'HUMAN',text:'Human'},
  ELF: {id:'ELF', text:'Elf'},
}

const CLASSES = {
  NONE:{id:'NONE', text:''},
  BEORNING: {id:'BEORNING', text:'Beorning'},
  BURGLAR:{id:'BURGLAR', text:'Burglar'},
  CAPTAIN:{id:'CAPTAIN', text: 'Captain'},
  CHAMPION:{id:'CHAMPION', text:'Champion'},
  GUARDIAN:{id:'GUARDIAN', text:'Guardian'},
  HUNTER:{id:'HUNTER', text:'Hunter'},
  LORE_MASTER:{id:'LORE_MASTER', text:'Lore-master'},
  MINSTREL:{id:'MINSTREL', text:'Minstrel'},
  RUNE_KEEPER:{id:'RUNE_KEEPER', text:'Rune-keeper'},
  WARDEN:{id:'WARDEN', text:'Warden'}
}

const ACTION_TYPES = {
  CHARACTER_ADDED:'CHARACTER_ADDED',
  CHARACTER_SELECTED: 'CHARACTER_SELECTED',
  CHARACTER_UPDATED:'CHARACTER_UPDATED',
  CHARACTER_DELETED:'CHARACTER_DELETED',
  DEED_UPDATED: 'DEED_UPDATED',
  DEED_SELECTED: 'DEED_SELECTED',
  DEED_COMPLETED: 'DEED_COMPLETED',
  DEED_CATEGORY_CHANGED: 'DEED_CATEGORY_CHANGED',
  DEED_SUBCATEGORY_CHANGED: 'DEED_SUBCATEGORY_CHANGED',
  INITIALIZATION: 'INITIALIZATION',
  INITIALIZATION_DONE: 'INITIALIZATION_DONE',
  WINDOW_RESIZE: 'WINDOW_RESIZE',
  MENU_UPDATE: 'MENU_UPDATE',
}

const DEED_CATEGORIES = {
  CLASS:0,
  RACE:1,
  'SHADOWS OF ANGMAR':2,
  'THE MINES OF MORIA':3,
  'ALLIES TO THE KING':4,
  'THE STRENGTH OF SAURON':5,
  'THE BLACK BOOK OF MORDOR':6,
  REPUTATION:7,
  ERIADOR:8,
  RHOVANION:9,
  GONDOR:10,
  MORDOR:11,
  SKIRMISH:12,
  "INSTANCES SHADOWS OF ANGMAR":13,
  "INSTANCES MINES OF MORIA":14,
  "INSTANCES LOTHLORIEN":15,
  "INSTANCES MIRKWOOD":16,
  "INSTANCES IN THEIR ABSENCE":17,
  "INSTANCES RISE OF ISENGUARD":18,
  "INSTANCES ROAD TO EREBOR":19,
  "INSTANCES ASHES OF OSGILIATH":20,
  "INSTANCES BATTLE OF PELENNOR":21,
  "SOCIAL, EVENTS, AND HOBBIES":22,
  SPECIAL:23
}

const SCREEN_SIZES = {
  SMALL: 576,
  MEDIUM: 768,
  LARGE: 1024,
  XLARGE: 1200
}

const BASE_URL = process.env.NODE_ENV === 'production' ? '/lotro-cl' : '';

export {RACES, CLASSES, ACTION_TYPES, DEED_CATEGORIES, SCREEN_SIZES, BASE_URL};
